export const CHAT_REPLY_DELAY_MS = 1500;
export const SLEEP_DELAY_MS = 10_000;
export const CREDITS_EXIT_BANNER_DURATION_MS = 5_000;

export const MIN_USER_MESSAGES_BEFORE_SLEEP = 2;
export const USER_MESSAGES_SLEEP_COOLDOWN = 2;
export const RESPONSE_HISTORY_LIMIT = 12;
